name: CI/CD Pipeline - Déploiement Production

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    name: Construire et Pousser les images Docker
    runs-on: ubuntu-latest

    steps:
      - name: 1. Récupérer le code
        uses: actions/checkout@v4

      - name: 2. Se connecter au GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: 3. Construire et Pousser l'image Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/syphaxalili/b2connect-store-backend:latest
          
      - name: 4. Construire et Pousser l'image Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/syphaxalili/b2connect-store-frontend:latest
          build-args: |
            VITE_API_URL=${{ vars.VITE_API_URL }}
            VITE_STRIPE_PUBLISHABLE_KEY=${{ vars.VITE_STRIPE_PUBLISHABLE_KEY }}
            
  deploy:
    name: Déployer sur le VPS
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: 1. Configurer la clé SSH privée
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: 2. Se connecter au VPS et déployer
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Aller dans le dossier du projet
            cd /var/www/b2connect-store
            
            # Mettre à jour le 'docker-compose.yml'
            git pull

            # Se connecter à GHCR
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin
            
            # Télécharger les nouvelles images depuis GHCR
            docker-compose pull
            
            # Relancer les conteneurs (en arrière-plan)
            # Docker Compose ne relancera que les services dont l'image a changé
            docker-compose up -d --no-build
            
            # Nettoyer les anciennes images
            docker image prune -f